name: produce trash

# Run every hour on the hour
on:
  schedule:
    - cron: '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: do commits
        run: |
          for i in {1..10}; do git commit -m "test" --allow-empty; done
          git push origin master
